import { writeFileSync } from "node:fs";

export default class DebugLoggerPlugin {
	static register(hooks) {
		// Event Logging
		hooks.addAction(
			"project_initialized",
			async ({ projectId, projectPath }) => {
				console.log(
					`[EVENT] Project Initialized: ${projectId} at ${projectPath}`,
				);
			},
		);

		hooks.addAction("job_started", async ({ jobId, type }) => {
			console.log(`[EVENT] Job Started: ${jobId} (Type: ${type})`);
		});

		// Visual identification in the model prompt
		hooks.addAction("TURN_SYSTEM_PROMPT_AFTER", async (slot) => {
			if (process.env.SNORE_DEBUG === "true") {
				slot.add("\n--- SNORE Debug Mode Active ---", 999);
			}
		});

		// PRETTIFIED AUDIT: Write the full exchange to a Markdown file
		hooks.addAction(
			"ask_completed",
			async ({ jobId, sessionId, model, request, response, usage }) => {
				if (process.env.SNORE_DEBUG !== "true") return;

				const auditFile = "audit_last_turn.md";
				const timestamp = new Date().toISOString();

				const systemMessage =
					request.find((m) => m.role === "system")?.content || "";
				const userMessage =
					request.find((m) => m.role === "user")?.content || "";
				const assistantMessage = response?.content || "EMPTY_RESPONSE";

				const markdown = [
					`# SNORE Turn Audit - ${timestamp}`,
					"",
					"## Metadata",
					`- **Job ID:** \`${jobId}\``,
					`- **Session ID:** \`${sessionId}\``,
					`- **Model:** \`${model}\``,
					`- **Tokens:** ${usage?.total_tokens || 0} (Prompt: ${usage?.prompt_tokens || 0}, Completion: ${usage?.completion_tokens || 0})`,
					"",
					"## System Prompt",
					"```xml",
					systemMessage,
					"```",
					"",
					"## User Prompt",
					"```xml",
					userMessage,
					"```",
					"",
					"## Assistant Response",
					"```text",
					assistantMessage,
					"```",
					"",
					"---",
					"_Generated by SNORE DebugLoggerPlugin_",
				].join("\n");

				try {
					writeFileSync(auditFile, markdown);
					console.log(`[DEBUG] Audit log written to: ${auditFile}`);
				} catch (err) {
					console.error(`[DEBUG] Failed to write audit log: ${err.message}`);
				}
			},
		);
	}
}
